feign:
  options:
    readTimeout: 60000
    connectTimeout: 30000
  httpclient:
    enabled: false
  okhttp:
    enabled: true      
  hystrix:
    enabled: true

hystrix:
  threadpool:
    # 服务名，填写default为所有服务
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: ${HYSTRIX_THREADPOOL_DEFAULT_CORESIZE_GW:128}
      maximumSize: ${HYSTRIX_THREADPOOL_DEFAULT_MAXIMUMSIZE_GW:256}
  command:
    # 服务名，填写default为所有服务
    default:
      circuitBreaker:
        requestVolumeThreshold: 1000
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
    ibps-business-provider:
      circuitBreaker:
        requestVolumeThreshold: 1000
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 240000
    
# ribbon全局设置
ribbon:
  eureka:
    # 会影响eureka注册时负载，使用eureka注册时必须设置true
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  # 请求负载的超时时间
  ReadTimeout: 15000
  # 请求连接的超时时间
  ConnectTimeout: 15000
  # 对当前实例的重试次数
  MaxAutoRetries: 0
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  # 是否所有操作都重试
  OkToRetryOnAllOperations: false  
  
## ribbon局部设置
ibps-business-provider:
  ribbon:
    # 请求负载的超时时间
    ReadTimeout: 60000
    # 请求连接的超时时间
    ConnectTimeout: 60000
    # 对当前实例的重试次数
    MaxAutoRetries: 0
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 1
    # 是否所有操作都重试
    OkToRetryOnAllOperations: false 