feign:
  options:
    readTimeout: 30000
    connectTimeout: 15000
  httpclient:
    enabled: false
  okhttp:
    enabled: true  
  hystrix:
    enabled: true

hystrix:
  threadpool:
    # 服务名，填写default为所有服务
    default:
      allowMaximumSizeToDivergeFromCoreSize: true
      coreSize: ${HYSTRIX_THREADPOOL_DEFAULT_CORESIZE:128}
      maximumSize: ${HYSTRIX_THREADPOOL_DEFAULT_MAXIMUMSIZE:256}
  command:
    # 服务名，填写default为所有服务
    default:
      circuitBreaker:
        requestVolumeThreshold: 1000
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
    ibps-business-provider:
      circuitBreaker:
        requestVolumeThreshold: 1000
        sleepWindowInMilliseconds: 5000
        errorThresholdPercentage: 50
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 100
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 120000
            
# ribbon全局设置
ribbon:
  eureka:
    # 会影响eureka注册时负载，使用eureka注册时必须设置true
    enabled: true  
  httpclient:
    enabled: false
  okhttp:
    enabled: true  
  # org.springframework.cloud.netflix.ribbon.RibbonEagerLoadProperties
  eager-load:
    enabled: true
    clients: 
    - ibps-oauthserver-provider
    - ibps-platform-provider
    - ibps-business-provider
    - ibps-form-provider
    - ibps-bpmn-provider
  # 请求负载的超时时间，应该小于网关的设置
  ReadTimeout: 7500
  # 请求连接的超时时间，应该小于网关的设置
  ConnectTimeout: 7500
  # 对当前实例的重试次数
  MaxAutoRetries: 0
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 1
  # 是否所有操作都重试
  OkToRetryOnAllOperations: false  
  
## ribbon局部设置
ibps-business-provider:
  ribbon:
    # 请求负载的超时时间
    ReadTimeout: 15000
    # 请求连接的超时时间
    ConnectTimeout: 15000
    # 对当前实例的重试次数
    MaxAutoRetries: 0
    # 切换实例的重试次数
    MaxAutoRetriesNextServer: 1
    # 是否所有操作都重试
    OkToRetryOnAllOperations: false  